POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "id": "df8d6ed0-654d-11ef-a42d-47d232affced",
  "description": "Routine check-up, patient in good health.",
  "date": "2024-08-26",
  "specialist": "Jane Foster, MD",
  "diagnosisCodes": ["Z57.1", "Z74.3", "M51.2"],
  "type": "HealthCheck",
  "healthCheckRating": 0
}

